#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

TEST=$("$SPLUNK_HOME/bin/splunk" btool --app=@app_id@ app list | awk -F " = " '/^state / {print $2}')
if [ $TEST == "disabled" ]; then
  cat << EOF
chunked 1.0,66,0
{ "action": "getinfo", "finished": true, "error": "PSC Disabled"}

EOF
  exit 1
fi

# https://splunk.atlassian.net/browse/SPL-237604, ensure execution bit is set on python binary
chmod +x "${SCRIPT_DIR}/../@version_dir@/bin/python" > /dev/null 2>&1 || true
chmod +x "${SPLUNK_HOME}/var/run/splunk/noah_tmp/@app_id@/bin/linux_x86_64/@version_dir@/bin/python" > /dev/null 2>&1 || true

exec "${SCRIPT_DIR}/../@version_dir@/bin/python" "$@"
