variables:
  # Vault-required variable: path of the cwd to allow docker-based operations to work
  CREDS_SECRET_ROOT: $CI_PROJECT_DIR
  GENERIC_DEPLOY_PROD_ROLE: artifactory:v2/cloud/role/psc-protected-role
  GENERIC_DEPLOY_TEST_ROLE: artifactory:v2/cloud/role/psc-unprotected-role
  VERSION_OVERRIDE: 4.1.2 # Change this for temp version update, note: this is only effective for MR and master builds, tag builds uses git tag as version

stages:
  - publish

include:
  - project: 'prodsec/scp-scanning/gitlab-checkmarx'
    ref: latest
    file: '/templates/.sast_scan.yml'

publish:
  image: ${LINUX_BUILD_IMAGE}
  stage: publish
  dependencies:
    - build-linux
#    - build-windows
#    - build-mac-x86_64
#    - build-mac-arm64
  before_script:
    - creds-helper init
    - eval $(creds-helper artifactory --eval $GENERIC_DEPLOY_ROLE)
  script:
    - make publish
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
      variables:
        GENERIC_DEPLOY_ROLE: $GENERIC_DEPLOY_TEST_ROLE
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        GENERIC_DEPLOY_ROLE: $GENERIC_DEPLOY_PROD_ROLE
        REPO: generic
    - if: $CI_COMMIT_TAG
      variables:
        GENERIC_DEPLOY_ROLE: $GENERIC_DEPLOY_PROD_ROLE
        REPO: generic
