name: build/venv
channels:
  - pytorch
  - conda-forge
dependencies:
  - boto3==1.17
  - botocore==1.20
  - bottle==0.12.23
  - chardet==3.0.4
  - future==0.18.3
  - networkx==3.0
  - numpy==1.23.0
  - python==3.8.19
  - pandas==1.1.5
  - psutil==5.8.0
  - ruptures==1.1.9
  - scipy==1.10
  - setuptools=70.0.0
  - statsmodels==0.13.2
  - scikit-learn==1.0.1
  - onnx==1.16
  - onnxruntime=1.18.1
  - openssl==3.3.1