name: psc
channels:
  - pytorch
  - conda-forge
dependencies:
  - boto3==1.17
  - botocore==1.20
  - bottle==0.12.20
  - chardet==3.0.4
  - fastdtw==0.3.4
  - future==0.18.2
  - idna==3.7
  - pandas==1.1.5
  - psutil==5.8.0
  - python==3.8.10
  - pytorch==1.11.0
  - networkx==2.5.1
  - numpy==1.22.0
  - requests==2.32.0
  - scipy==1.10.0
  - setuptools==65.5.1
  - statsmodels==0.12.2
  - scikit-learn==0.24.2
  - stumpy==1.12.0
  - tbb==2021.5
  - tqdm==4.66.3
  - transformers==4.38.0
  - cpuonly=2.0
  - onnx==1.15.0
  - onnxruntime==1.10.0
  - pydantic==1.10.13
  - pytorch==1.13.1
  - urllib3==1.26.19
  - watchdog==2.1.7