name: build/venv
channels:
  - conda-forge
dependencies:
  - boto3==1.17
  - bottle==0.12.23
  - chardet==3.0.4
  - future==0.18.3
  - networkx==3.0
  - numpy==1.23.0
  - onnx==1.16.0
  - onnxruntime==1.18.1
  - openssl==3.3.2
  - pandas==1.1.5
  - psutil==5.8.0
  - python==3.9.19
  - ruptures==1.1.9
  - scipy==1.10
  - scikit-learn==1.5.1
  - statsmodels==0.13.2
