name: psc
channels:
  - pytorch
  - conda-forge
dependencies:
  - boto3==1.24.2
  - botocore==1.27.2
  - chardet==4.0.0
#  - fastdtw==0.3.4
  - future==0.18.3
  - pandas==1.5.3
  - psutil==5.8.0
  - python==3.8.10
  - pytorch==1.13.1
  - networkx==2.8.4
  - numpy==1.24.3
  - scipy==1.10.1
  - statsmodels==0.14.0
  - scikit-learn==1.3.0
  - stumpy==1.11.1
  - tbb==2021.5
  - transformers==4.38.0
  - cpuonly=2.0
  - onnx==1.15.0
  - onnxruntime==1.10.0
  - pydantic>=1.10.13,<2.4.1
  - watchdog==2.1.7
  - pip:
    - bottle==0.12.20