name: psc
channels:
  - pytorch
  - conda-forge
dependencies:
  - boto3==1.17
  - bottle==0.12.23
  - chardet==3.0.4
  - fastdtw==0.3.4
  - future==0.18.3
  - pandas==1.1.5
  - psutil==5.8.0
  - python==3.9.19
  - pytorch==2.2.2
  - networkx==3.0
  - numpy==1.23
  - ruptures==1.1.9
  - scipy==1.10
  - statsmodels==0.13.2
  - scikit-learn==1.5.1
  - stumpy==1.12.0
  - tbb==2021.5
  - transformers==4.38.1
  - cpuonly
  - onnx==1.16
  - onnxruntime==1.18.1
  - pydantic==1.10.13
  - watchdog==2.1.7
