name: psc
channels:
  - pytorch
  - conda-forge
dependencies:
  - boto3==1.17
  - botocore==1.20
  - bottle==0.12.23
  - chardet==3.0.4
  - fastdtw==0.3.4
  - future==0.18.3
  - pandas==1.1.5
  - psutil==5.8.0
  - python==3.8.12
  - pytorch==1.13.1
  - networkx==3.0
  - numpy==1.23.0
  - scipy==1.10.0
  - statsmodels==0.13.2
  - scikit-learn==0.24.2
  - stumpy==1.12.0
  - tbb==2021.5
  - transformers==4.38.1
  - cpuonly=2.0
  - onnx==1.14.0
  - onnxruntime==1.15.1
  - pydantic==1.10.13
  - watchdog==2.1.7
  - pip:
      - setuptools==65.5.1