FROM ubuntu:16.04

ENV PSC_HOME /var/tmp/home

RUN apt-get update  && apt-get install -y --no-install-recommends apt-utils && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y wget \
        unzip \
        curl \
        vim \
        net-tools \
        sudo \
        python2.7 \
        python-pip \
        git \
        rsync \
    && mkdir -p ${PSC_HOME}

WORKDIR ${PSC_HOME}

CMD [ "/bin/bash" ]