FROM debian:buster-slim

ENV PSC_HOME /var/tmp/home

RUN apt-get -qq update -y \
    && apt-get -qq upgrade -y \
    && apt-get -qq install curl \
        unzip \
        net-tools \
        git \
        rsync \
    && rm -rf /var/lib/apt/lists/*

WORKDIR ${PSC_HOME}

CMD [ "/bin/bash" ]
