# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR "C:\temp"
COPY files .

RUN Set-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\FileSystem" -Name 'LongPathsEnabled' -Value 1; `
    Set-ExecutionPolicy RemoteSigned -force; `
    .\chocolatey-install.ps1; `
    choco install 7zip git powershell-core -y;
    
USER splunker
ENTRYPOINT powershell.exe
