[launcher]
description = Python for Scientific Computing
author = Splunk
version = @version@

[package]
id = Splunk_SA_Scientific_Python_@platform@

[install]
is_configured = 0
build = @build@

[ui]
is_visible = false
label = Python for Scientific Computing
